### ISSUE TITLE
SyntaxError: invalid token in setup.py, line 36: "os.chmod(fname, 0755)"

### ISSUE THREAD

**Issue by jordanade** [kfix/SleepProxyServer#2]
Trying to install on Ubuntu 16.04.3 LTS (Xubuntu Xenial)
```
$ pip install git+https://github.com/kfix/SleepProxyServer.git
Collecting git+https://github.com/kfix/SleepProxyServer.git
  Cloning https://github.com/kfix/SleepProxyServer.git to /tmp/pip-r9tqmmsi-build
Collecting dnspython (from SleepProxyServer==0.1)
  Downloading dnspython-1.15.0-py2.py3-none-any.whl (177kB)
    100% |████████████████████████████████| 184kB 2.0MB/s 
Collecting gevent (from SleepProxyServer==0.1)
  Downloading gevent-1.2.2-cp35-cp35m-manylinux1_x86_64.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 127kB/s 
Collecting netifaces (from SleepProxyServer==0.1)
  Downloading netifaces-0.10.6.tar.gz
Collecting scapy (from SleepProxyServer==0.1)
  Downloading scapy-2.3.3.tgz (1.4MB)
    100% |████████████████████████████████| 1.4MB 196kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qxs1o84d/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qxs1o84d/scapy/
```

**Comment by kfix** [comment]
That's a bug in scapy, not SleepProxyServer.

**Comment by jordanade** [comment]
Well, I somehow managed to install scapy (using pip2.7), now I'm getting this:
```
$ pip install git+https://github.com/kfix/SleepProxyServer.git
Collecting git+https://github.com/kfix/SleepProxyServer.git
  Cloning https://github.com/kfix/SleepProxyServer.git to /tmp/pip-atuxRp-build
Requirement already satisfied: dnspython in /usr/lib/python2.7/dist-packages (from SleepProxyServer==0.1)
Requirement already satisfied: gevent in /usr/lib/python2.7/dist-packages (from SleepProxyServer==0.1)
Requirement already satisfied: netifaces in /usr/lib/python2.7/dist-packages (from SleepProxyServer==0.1)
Requirement already satisfied: scapy in /usr/local/lib/python2.7/dist-packages (from SleepProxyServer==0.1)
Collecting py2-ipadddress (from SleepProxyServer==0.1)
  Could not find a version that satisfies the requirement py2-ipadddress (from SleepProxyServer==0.1) (from versions: )
No matching distribution found for py2-ipadddress (from SleepProxyServer==0.1)
```

**Comment by kfix** [comment]
Please stop filing issues about install. I’m not pip tech support.
